# .appveyor.yml

# Build version
version: '1.41.{build}'

# Use the latest available toolchain
image: Visual Studio 2019

# fetch repository as zip archive
shallow_clone: true

# PRs do not increment the build number
pull_requests:
  do_not_increment_build_number: true

# Build configurations
platform:
  - x86
  - x64

# Default environment variables
environment:
  _IS_BUILD_CANARY: false
  _RELEASE_NAME: SteamworksSDK
  # Use Python 3.x
  PYTHON: "C:\\Python38-x64"
  PYTHON_VERSION: "3.8.x"
  PYTHON_ARCH: "64"

# Prepare Cpp environment
before_build:
  - cmd: |
      set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_REPO_TAG_NAME) {
        $env:APPVEYOR_BUILD_VERSION = $env:APPVEYOR_BUILD_VERSION.Substring(0,$env:APPVEYOR_BUILD_VERSION.LastIndexOf('.')) + ".0"
        $env:_RELEASE_NAME = $env:_RELEASE_NAME + "-v" + $env:APPVEYOR_BUILD_VERSION
      } else {
        $env:_RELEASE_NAME = $env:_RELEASE_NAME + "-Canary"
        $env:APPVEYOR_REPO_TAG_NAME = "canary"
        $env:_IS_BUILD_CANARY = "true"
      }

build_script:
  - cmd: |
      md .dist\bin\steam
      md .dist\lib\steam
      md .dist\include\steam
      mv steamworks_sdk/public/steam/*.h .dist/include/steam

for:
  -
    matrix:
      only:
        - platform: x86
    after_build:
        - cmd: |
            mv steamworks_sdk/redistributable_bin/*.lib .dist/lib/steam/
            mv steamworks_sdk/redistributable_bin/*.dll .dist/bin/steam/
            mv steamworks_sdk/redistributable_bin/linux32/*.so .dist/lib/steam/
            mv steamworks_sdk/redistributable_bin/osx32/*.dylib .dist/lib/steam/
            mv steamworks_sdk/public/steam/lib/win32/*.lib .dist/lib/steam/
            mv steamworks_sdk/public/steam/lib/win32/*.dll .dist/bin/steam/
            mv steamworks_sdk/public/steam/lib/linux32/*.so .dist/lib/steam/
            mv steamworks_sdk/public/steam/lib/osx32/*.dylib .dist/lib/steam/
  -
    matrix:
      only:
        - platform: x64
    after_build:
        - cmd: |
            mv steamworks_sdk/redistributable_bin/win64/*.lib .dist/lib/steam/
            mv steamworks_sdk/redistributable_bin/win64/*.dll .dist/bin/steam/
            mv steamworks_sdk/redistributable_bin/linux64/*.so .dist/bin/steam/
            mv steamworks_sdk/public/steam/lib/win64/*.lib .dist/lib/steam/
            mv steamworks_sdk/public/steam/lib/win64/*.dll .dist/bin/steam/
            mv steamworks_sdk/public/steam/lib/linux64/*.so .dist/lib/steam/

# Do not run unit tests
test: off

# Package artifacts
artifacts:
  - path: .dist
    name: ${_RELEASE_NAME}_${PLATFORM}
    type: zip

# Create a GitHub release for every tag
deploy:
  # Deploy only when new tags are pushed
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: ${_RELEASE_NAME}
    artifact: ${_RELEASE_NAME}_${PLATFORM}
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      _IS_BUILD_CANARY: false
  # Deploy on each commit
  - provider: GitHub
    tag: ${appveyor_repo_tag_name}
    release: ${_RELEASE_NAME} v${appveyor_build_version}
    artifact: ${_RELEASE_NAME}_${PLATFORM}
    prerelease: true
    force_update: true
    auth_token:
      secure: SXUyBqg8+wl9fn3xHV2Br0xDH65EyPAnFwJbwcg94wIesv9osQEefC3zxu9iDTUh
    on:
      _IS_BUILD_CANARY: true
    description: |
      This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
